server:
  port: 8081

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

swagger:
  enable: true
