server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345678
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis-plus:
  mapper-locations: classpath:com/example/login/mybatis/mappers/*Mapper.xml
  type-aliases-package: com.example.login.model
  global-config:
    db-config:
      #表名、是否使用下划线命名,默认为true
      tableUnderline: true
  configuration:
    #指将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
    #开启二级缓存，默认开启
    cache-enabled: false
    jdbc-type-for-null: 'null'

swagger:
  enable: true

#showSql
logging:
  level:
    com:
      example:
        mapper : debug